name: peakpuller_testing
channels:
  - conda-forge
  - bioconda
dependencies:
  - caper
  - docker-py
  - croo    
  - bedtools
  - bwa
  - click
  - fastqc
  - git
  - h5py
  - mosdepth
  - multiqc
  - picard
  - pysam
  - qualimap
  - r-base
  - ruamel.yaml
  - samtools
  - snakemake-minimal >=5.8
