### REQUIRED ARGUMENTS BY USER
rawdir:
  '/scripts/test/fastq'
output_dir:
  '/output'
group1: [
  'simulated1',
  'simulated2'
]
group2: [
  'simulated3',
  'simulated4'
]
samples: [
  'simulated1',
  'simulated2',
  'simulated3',
  'simulated4'
]
ref:
  '/scripts/test/lambda-phage.fa'

cgi_annotation_file:
  'annotation/cgi-locations-hg38.csv.gz'
gene_annotation_file:
  'annotation/gene-locations-hg38.csv.gz'
repeat_masker_annotation_file:
  'annotation/repeat-masker-hg38.csv.gz'
transcript_start_site_file:
  'annotation/transcription-start-sites-hg38.csv.gz'

annotation_min_mapq:
  10
computing_threads:
  8
io_threads:
  8
min_cpg:
  5
min_diff:
  0.3
min_cov:
  5
rawsuffixregex:
  first:  '_1\.fastq'
  second: '_2\.fastq'
target_files: [
  'dmr/annotated-dmrs.csv',
  'qc/multiqc_report.html',
  'qc/methylation_metrics.csv'
]
dmr_tools: [
  'bsseq',
  #'camel',
  'metilene'
]

promoter_tss_distances: [
  -1000,
  1000
]
annotation_allowed_biotypes: [
  # protein coding genes
  'protein_coding',
  # lncRNA
  'non_coding',
  '3prime_overlapping_ncRNA',
  'antisense',
  'lincRNA',
  'retained_intron',
  'sense_intronic',
  'sense_overlapping',
  'macro_lncRNA',
  'bidirectional_promoter_lncRNA',
  # miRNA
  'miRNA'
]
repeat_masker_links: {
  'annotation/repeat-masker-hg38.csv.gz': 'https://uni-muenster.sciebo.de/s/LwMik3kKY83oVT0/download',
  'annotation/repeat-masker-hg19.csv.gz': 'https://uni-muenster.sciebo.de/s/tFPOT7weAc5eGLG/download'
}
